version: '3.8'
services:
  database:
    container_name: 'tg_db'
    image: postgres
    volumes:
      - tg_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'tg_db'
    ports:
      - '5432:5432'

volumes:
  tg_db:
    driver: local
